apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  namespace: solar-system
  labels:
    app: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - name: solar-system
          image: siddharth67/solar-system:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
#kubectl port-forward svc/solar-system-service -n solar-system 8080:80
