apiVersion: v1
kind: Namespace
metadata:
  name: solar-system
---
apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  namespace: solar-system
  labels:
    app: solar-system
spec:
  type: NodePort
  selector:
    app: solar-system
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30333
      protocol: TCP